config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  resources :favorites, only:[:show]
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :house_makers, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  resources :users do
    resource :follow,only: [:create, :destroy]
    resources :followings,only: [:index] 
    resources :followers,only: [:index] 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'

  validates :target_user_id, uniqueness: { scope: :user_id }
end

app/models/house_maker.rb
class HouseMaker < ApplicationRecord
  has_many :reviews, dependent: :destroy
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 100 }
  with_options presence: true do
    validates :body, :title

  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :house_maker
  validates :score,:content, presence: true, length: { maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  attachment :profile_image
  has_many :posts,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  validates :username, presence: true, length: { maximum: 10 }
  validates :profile, {length: {maximum: 24}}
  validates :maker_name, {length: {maximum: 12}}


  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end
  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def new_guest
    guest = User.find_or_create_by!(email: 'test@test.com') do |user|
      guest.password = SecureRandom.urlsafe_base64
    end
    sign_in guest
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/house_makers_controller.rb
class HouseMakersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @house_makers = HouseMaker.all
    @reviews = Review.all
    @q = HouseMaker.ransack(params[:q])
    @house_makers = @q.result(distinct: true)
  end

  def show
    @house_maker = HouseMaker.find(params[:id])
    @review = Review.new
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order("id DESC").page(params[:page]).per(5)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    if @comment.save
      redirect_to post_path(@post)
    else 
      render :show 
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else 
      render :new 
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post)
    else 
      render :edit
    end
  end


  def edit
    @post= Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path, alert: "不正なアクセスです"
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end


  private
  def post_params
    params.require(:post).permit(:title,:body,:image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show,:edit]
  
  def index
    @users = User.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @house_makers = HouseMaker.all
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです"
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新に成功しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:eimal,:profile,:profile_image,:have_house,:maker_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/house_makers_helper.rb
module HouseMakersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/house_makers/index.html.erb
<div class ="column mt-6">
</div>
<div class ="container">
  <div class="columns is-mobile is-centered">
    <div class="column is-four-fifths">
      <div class="box mt-6">
        <div class="container">
          <h1 class="title has-text-centered mb-4">
            ハウスメーカー一覧
          </h1>
        </div>
        <div class="box">
              <div class="has-text-centered">
        <%= search_form_for @q do |f| %>
        <nav class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="subtitle is-5">
        <strong>検索ワード</strong>
      </p>
    </div>
    <div class="level-item">
      <div class="field has-addons">
        <p class="control">
          <%= f.search_field :name_cont,class:"input", type:"text", placeholder:"検索ワード"%>
        </p>
        <p class="control">
          <%= f.submit "検索",class: "button" %>
          <%= link_to "全て表示" ,house_makers_path ,class:"button" %>
      </div>
    </div>
  </div>
</nav>
  </div>
  </div>
<% end %>
<div class="container">
<div class="columns is-centered">
<table class="table">
  <thead>
    <tr>
      <th class ="has-text-centered">メーカー名</th>
      <th class ="has-text-centered">評価</th>
      <th class ="has-text-centered">点数</th>
      <th class ="has-text-centered">レビュー数</th>
    </tr>
  </thead>
  <% @house_makers.each do |house_maker| %>
    <tfoot>
      <tr>
        <th><%= link_to house_maker.name, house_maker_reviews_path(house_maker) %></th>
        <th class ="has-text-centered">
          <div class="star-rating mb-2">
            <div class="star-rating-front" style="width: <%= house_maker.review_score_percentage %>%">
              ★★★★★
            </div>
            <div class="star-rating-back">
              ★★★★★
            </div>
          </div>
        </th>
        <th class ="has-text-centered">
          <div class="average-score-display ml-3 pt-2">
            <%= house_maker.avg_score %>点
          </div>
        </th>
        <th class ="has-text-centered">
        （<%= house_maker.reviews.count %>件）
        </th>
      </tr>
    </tfoot>
  <% end %> 
</table>
</div>
</div>

app/views/house_makers/show.html.erb
  
<section class="hero is-success mt-6">
  <div class="hero-body ">
    <div class="container">
      <h1 class="title has-text-centered mt-3">
        <%= @house_maker.name %>の評価をつける
      </h1>
    </div>
  </div>
</section>
<section class="section mt-1">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class ="box">
          <div class="card mb-6">
            <header class="card-header">
              <p class="card-header-title">
                <%= @house_maker.name %>
              </p>
            </header>
            <div class="card-content">
            <%= link_to house_maker_reviews_path(@house_maker) do %>
              <div class="content average-score">
                <div class="star-rating mb-2">
                  <div class="star-rating-front" style="width: <%= @house_maker.review_score_percentage %>%">★★★★★</div>
                  <div class="star-rating-back">★★★★★</div>
                </div>
                <div class="average-score-display ml-3 pt-2">
                  <%= @house_maker.avg_score %>点（<%= @house_maker.reviews.count %>件のレビュー）
                </div>
              </div>
            <% end %>
            </div>
          </div>
          <%= render 'reviews/form', review: @review, house_maker: @house_maker %>
        </div>
      </div>
    </div>
  </div>
</section>