config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  resources :favorites, only:[:show]
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :house_makers, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  resources :users do
    resource :follow,only: [:create, :destroy]
    resources :followings,only: [:index] 
    resources :followers,only: [:index] 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'

  validates :target_user_id, uniqueness: { scope: :user_id }
end

app/models/house_maker.rb
class HouseMaker < ApplicationRecord
  has_many :reviews, dependent: :destroy
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 100 }
  with_options presence: true do
    validates :body, :title

  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :house_maker
  validates :score,:content, presence: true, length: { maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  attachment :profile_image
  has_many :posts,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  validates :username, presence: true, length: { maximum: 10 }
  validates :profile, {length: {maximum: 24}}
  validates :maker_name, {length: {maximum: 12}}


  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end
  

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.active_relationships.create(target_user_id: params[:user_id])

    redirect_to [:user, { id: params[:user_id] }]
  end

  def destroy
    current_user.active_relationships.find_by(target_user_id: params[:user_id]).destroy

    redirect_to [:user, { id: params[:user_id] }]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def new_guest
    guest = User.find_or_create_by!(email: 'test@test.com') do |user|
      guest.password = SecureRandom.urlsafe_base64
    end
    sign_in guest
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order("id DESC").page(params[:page]).per(5)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    if @comment.save
      redirect_to post_path(@post)
    else 
      render :show 
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else 
      render :new 
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post)
    else 
      render :edit
    end
  end


  def edit
    @post= Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path, alert: "不正なアクセスです"
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end


  private
  def post_params
    params.require(:post).permit(:title,:body,:image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show,:edit]
  
  def index
    @users = User.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    @house_makers = HouseMaker.all
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです"
    end
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "更新に成功しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:eimal,:profile,:profile_image,:have_house,:maker_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/house_makers_helper.rb
module HouseMakersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<%=form_for @post do |f|%>

  <%=f.label :body %>
  <%= f.text_area :body %>

  <%=f.label :image %>
  <%= f.attachment_field :image %>
  
  <%=f.submit "更新"%>


<div class="container">
  <div class="columns is-centered">
    <div class="column is-6">

    </div>
  </div>
</div>
<div class="container">
  <div class="columns is-centered mt-6">
    <div class="column is-6">
      <div class="field">
        <label class="label">タイトル</label>
        <%= f.text_field :title, class: "input", placeholder: "Title" %>
      </div>


<div class="field">
    <label class="label">アップロード画像</label>
    <div class="control">
      <span class="file-cta">
        <%= f.attachment_field :image, class: "file-input" %>
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
          <span class="file-label">
          <%=f.label :image, "ファイルをアップロード"%>
          </span>
      </span>
    </div>  
  </div>
      <div class="field">
  <label class="label">投稿内容</label>
  <div class="control">
    <%= f.text_area :body, class: "textarea", placeholder: "Textarea" %>
  </div>
</div>
<div class="field is-grouped">
  <div class="control">
  <%= f.submit "更新", class: "button is-success" %>
  </div>
  <div class="control">
    <%= link_to posts_path do %>
    <div class="button is-link is-light">戻る</div>
    <% end %>
  </div>
</div>
    </div>
  </div>
</div>




<% end %>

app/views/posts/index.html.erb
<div class ="column mt-6">
</div>
<div class ="container">
   <div class="columns is-mobile is-centered">
      <div class="column is-four-fifths">
         <section class="box">
            <div class="container">
               <h1 class="title has-text-centered mb-4">
               投稿一覧
               </h1>
            </div>
            <section class="box">
               <div class="has-text-centered">
                  <nav class="level">
                     <div class="level-left">
                        <div class="level-item">
                           <p class="subtitle is-5">
                           <strong>検索ワード</strong>
                           </p>
                        </div>
                        <div class="level-item">
                           <%= search_form_for @q do |f| %>
                           <div class="field has-addons">
                              <p class="control">
                                 <%= f.search_field :title_cont,class:"input", type:"text", placeholder:"検索ワード"%>
                              </p>
                              <p class="control">
                                 <%= f.submit "検索",class: "button" %>
                              </p>
                           </div>
                           <% end %>
                        </div>
                     </div>
                     <%= link_to "全て表示" ,posts_path ,class:"button" %>
                  </nav>
               </div>
            </section>
            <% @posts.each do |post|%> 
            <div class="box media mb-0 mt-0 pb-2 pt-2">
               <figure class="media-left">
                  <p class="image is-32x32">
                     <%= link_to user_path(post.user_id) do %>
                        <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.png" %>
                     <% end %>
                  </p>
               </figure>
               <div class="media-content">
                  <%= link_to user_path(post.user_id) do %>
                     <%= post.user.username %>さん：
                  <% end %>
                  <strong>
                     <%= link_to post_path(post) do %>
                        <%= post.title %>
                     <% end %>
                  </strong>
                  <% if post.image_id == nil %>
                  <% else %>
                     <%= link_to post_path(post) do %>
                        画像あり
                     <% end %>
                  <% end %>
                  <div class ="has-text-right is-size-7">
                     <%= link_to post_path(post) do %>
                        <span class="icon is-small"><i class="fas fa-reply"></i></span>
                        <%= post.comments.count %>
                     <% end %>
                     <% if user_signed_in? %> 
                        <% if current_user.already_favorited?(post)%>
                           <%= link_to post_favorites_path(post), method: :delete do %>
                              <span style="color: #ff5252"><span style="font-size: 100%"><i class="fa fa-heart faa-wrench animated-hover"></i></span></span>
                           <% end %>
                        <% else %>
                           <%= link_to post_favorites_path(post), method: :post do %>
                              <i class ="far fa-heart faa-wrench animated-hover"></i>
                           <% end %>
                        <% end %>
                        <%= post.favorites.count %>
                     <% else %>
                        <%= link_to post_favorites_path(post), method: :delete do %>
                           <i class ="far fa-heart faa-wrench animated-hover"></i>
                           <%= post.favorites.count %>
                        <% end %>
                     <% end %>
                     <%= link_to post_path(post) do %>
                        詳細
                     <% end %>
                     <% if current_user == post.user %>
                        <%= link_to post_path(post), method: :delete, data:{confirm: "削除しますか？"} do %>
                           削除
                        <% end %>
                     <% end %>
                     <%= post.updated_at.strftime("%Y-%m-%d %H:%M") %>投稿
                  </div>
               </div>
            </div>
            <% end %>
            <div class="card mt-3 mb-0">
               <%= paginate @posts,class: "pagination is-centered" %>
            </div>
         </section>
      </div>
   </div>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div class="notification is-danger">
    <h2><%= @post.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %> 
<%= form_for @post do |f|%>
<div class ="container">
 <div class ="column mb-6">
 </div>
</div>
<div class ="container">
<div class="columns is-mobile is-centered">
<div class ="column is-half">
<div class ="box">
<div class="field">
  <label class="label">タイトル</label>
  <div class="control">
    <%= f.text_field :title, class: "input", placeholder: "Title" %>

  </div>
</div>
<div class="field">
    <label class="label">アップロード画像</label>
    <div class="control">
      <span class="file-cta">
        <%= f.attachment_field :image, class: "file-input" %>
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
          <span class="file-label">
          <%=f.label :image, "ファイルをアップロード"%>
          </span>
      </span>
    </div>  
  </div>

<div class="field">
  <label class="label">投稿内容</label>
  <div class="control">
    <%= f.text_area :body, class: "textarea", placeholder: "Textarea" %>
  </div>
</div>
<div class="field is-grouped">
  <div class="control">
  <%= f.submit "投稿", class: "button is-success" %>
  </div>
  <div class="control">
    <%= link_to posts_path do %>
    <div class="button is-link is-light">戻る</div>
    <% end %>
  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class ="column mb-6">
</div>
<div class ="container">
  <div class="columns is-centered">
    <div class="column is-10">
    <div class ="box">
      <div class="title has-text-centered">
        <%= @post.title %>
      </div>
      <article class="media mt-6">
        <figure class="media-left">
          <p class="image is-64x64">
            <%=link_to user_path(@post.user) do %>
            <%= attachment_image_tag @post.user,:profile_image, fallback: "no-image.png" %>
            <% end %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>
                <%=link_to user_path(@post.user) do %>
                <%= @post.user.username %>
                <% end %>
              </strong>
              <br>
							<%= simple_format @post.body %>
                <% if @post.image_id == nil %>
                <% else %>
                    <%= link_to post_path(@post) do %>
              <p class="image is-128x128">
							    <%= attachment_image_tag @post, :image %>
              </p>
                    <% end %>
                <% end %>
                <div class ="has-text-right">
                  <% if current_user.already_favorited?(@post)%>
                    <%= link_to post_favorites_path(@post), method: :delete do %>
                      <span style="color: #ff5252"><span style="font-size: 100%"><i class="fa fa-heart faa-wrench animated-hover"></i></span></span>
                    <% end %>
                    <% else %>
                    <%= link_to post_favorites_path(@post), method: :post do %>
                      <i class ="far fa-heart  faa-wrench animated-hover"></i>
                    <% end %>
                  <% end %>
                  <%= @post.favorites.count %>
                  <% if @post.user.id == current_user.id%>
                    <%= link_to "編集", edit_post_path(@post), class: "buttom"%>
                    <%= link_to post_path(@post), method: :delete, data:{confirm: "削除しますか？"} do %>
                    削除
                    <% end %>
                </div>
								<% end %>
            </p>
          </div>
				<% @comments.each do |comment| %>
          <article class="media">
            <figure class="media-left">
              <p class="image is-48x48">
                <%=link_to user_path(comment.user) do %>
                <%= attachment_image_tag comment.user,:profile_image, fallback: "no-image.png" %>
            <% end %>
              </p>
            </figure>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong>
										<%=link_to user_path(comment.user) do %>
										<%= comment.user.username %>
										<% end %>
									</strong>
                  <br>
										<%= comment.comment %>
                  <br>
									<% if comment.user.id == current_user.id%>
                    <%= link_to post_comment_path(@post, comment), method: :delete, data:{confirm: "削除しますか？"} do %>
                    <div class ="has-text-right">
                    削除
                    </div>
                    <% end %>
									<% end %>
                </p>
              </div>
            </div>
          </article>
				<% end %>
      <%= form_for [@post, @comment] do |f| %>
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <%= attachment_image_tag current_user,:profile_image, fallback: "no-image.png" %>
          </p>
        </figure>
        <div class="media-content">
          <div class="field">
            <p class="control">
              <div class="field">
                <p class="control">
                  <%= f.text_area :comment, class: "textarea", placeholder: "コメントを入力する"%>
                </p>
              </div>
            </p>
          </div>
          <div class="field">
            <p class="control">
                <%= f.submit '送信', class: "btn-sm btn-primary" %>
            </p>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %> 
<%=form_for @user do |f|%>

<div class="container">
  <div class="columns is-centered">
    <div class="column is-6">

    </div>
  </div>
</div>
<div class="container">
  <div class="columns is-centered mt-6">
    <div class="column is-6">
  <div class ="box black">
      <div class="field">
        <label class="label">ユーザーネーム</label>
        <div class="control has-icons-left has-icons-right">
          <%= f.text_field :username,class: "input" %>
          <span class="icon is-small is-left">
            <i class="fas fa-user"></i>
          </span>
          <span class="icon is-small is-right">
            <i class="fas fa-check"></i>
          </span>
        </div>
      </div>

      <div class="field">
        <label class="label">Email</label>
        <div class="control has-icons-left has-icons-right">
          <%= f.text_field :email, class: "input" %>
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
          <span class="icon is-small is-right">
            <i class="fas fa-exclamation-triangle"></i>
          </span>
        </div>
      </div>
      <div class="field">
        <label class="label">プロフィール画像</label>
        <div class="control">
          <span class="file-cta">
            <%= f.attachment_field :profile_image, class: "file-input" %>
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
            <%=f.label :profile_image, "ファイルをアップロード"%>
            </span>
          </span>
        </div>  
      </div>
      <div class="field">
        <label class="label">現在の状況</label>
        <div class="control">
          <div class="select">
              <%= f.select :have_house, {"これから建築": 1, "建築済み": 2}, { class: 'form-control' , required: true } %>
          </div>
        </div>
      </div>

      <div class="field">
        <label class="label">
          <% if @user.have_house == "1" %>
            <%=f.label :maker_name, "気になるメーカー"%>
          <% else %>
            <%=f.label :maker_name, "建築メーカー" %>
          <% end %>
        </label>
        <div class="control has-icons-left has-icons-right">
          <%= f.text_field :maker_name, class: "input" %>
          <span class="icon is-small is-left">
            <i class="fa fa-home"></i>
          </span>
          <span class="icon is-small is-right">
            <i class="fas fa-exclamation-triangle"></i>
          </span>
        </div>
      </div>

      <div class="field">
        <label class="label">プロフィール</label>
        <div class="control has-icons-left has-icons-right">
          <%= f.text_area :profile, class: "input textarea" %>
          <span class="icon is-small is-left">
            <i class="fa fa-user-circle"></i>
          </span>
          <span class="icon is-small is-right">
            <i class="fas fa-exclamation-triangle"></i>
          </span>
        </div>
      </div>
      <div class="field is-grouped">
        <div class="control">
          <%=f.submit "更新", class: "button"%>
        </div>
        <div class="control">
          <%= link_to user_path(current_user) ,class: "button" do  %>
          戻る
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<% end %>

app/views/users/index.html.erb
<div class ="column mt-6">
</div>
<div class ="container">
  <div class="columns is-mobile is-centered">
    <div class="column is-four-fifths">
      <div class="box">
        <div class="container">
          <h1 class="title has-text-centered mb-4">
            ユーザー一覧
          </h1>
        </div>
        <div class="box">
          <div class="has-text-centered">
          <%= search_form_for @q do |f| %>
            <nav class="level">
              <div class="level-left">
                <div class="level-item">
                  <p class="subtitle is-5">
                    <strong>検索ワード</strong>
                  </p>
                </div>
                <div class="level-item">
                  <div class="field has-addons">
                    <p class="control">
                      <%= f.search_field :username_or_maker_name_cont,class:"input", type:"text", placeholder:"検索ワード"%>
                    </p>
                    <p class="control">
                      <%= f.submit "検索",class: "button" %>
                  </div>
                </div>
              </div>
              <div class="level-right">
                <p class="level-item"><strong>状況：</strong></p>
                <div class="select">
                  <%= f.select :have_house_eq, {"指定なし": '', "これから建築": 1, "建築済み": 2}, { class: 'form-control' , required: true } %>
                </div>
                <%= f.submit "検索",class: "button" %>
              </div>
              <%= link_to "全て表示" ,users_path ,class:"button" %>
            </nav>
          <% end %>
          </div>
        </div>
          <div class="container">
            <div class="columns is-centered">
            <table class="table">
              <thead>
                <tr>
                  <th class ="has-text-centered">画像</th>
                  <th class ="has-text-centered">ユーザー名</th>
                  <th class ="has-text-centered">状況</th>
                  <th class ="has-text-centered">メーカー名</th>
                </tr>
              </thead>
              <% @users.each do |user| %>
                <tfoot>
                  <tr>
                    <th><p class="image is-32x32">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </p></th>
        <th class ="has-text-centered"><%=link_to user.username, user_path(user) %></th>
        <th class ="has-text-centered"><% if user.have_house == "1"%>
                  建築前
                <% else %>
                  建築済み
                <% end %></th>
        <th class ="has-text-centered">
                <%= user.maker_name%>
                </th>
        <th class ="has-text-centered"><%=user.posts.count%></th>
      </tr>
    </tfoot>
  <% end %> 
</table>
</div>
  <div class="card mt-3 mb-0">
    <%= paginate @users,class: "pagination is-centered" %>
  </div>
</div>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered">
         <% if @user == current_user%>
            マイページ
         <% else %>
            <%= @user.username %>のプロフィール
         <% end %>
      </h1>
    </div>
  </div>
</section>
   <div class ="container">
            <div class="column">
            <article class="box media">
            <figure class="media-left">
               <p class="image is-128x128">
               <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png" %>
               </p>
            </figure>
            <div class="media-content">
               <div class="content">
                  <p><strong>名前：<%= @user.username %></strong>
                  <%if @user.id == current_user.id%>
                     <%=@user.email%>
                  <% end %>
                  <strong>
                  <% if @user.have_house == "1" %>
                  気になるメーカー：
                  <% else %>
                  オーナー：
                  <% end %>
                  <%=@user.maker_name%>
                  </strong>
                  
                  <br>プロフィール<br>
                  <br><%=@user.profile%><br>
                  </p>
                  <%if @user.id == current_user.id%>
                  <td>
                  <%= link_to edit_user_path(@user), class: "button" do %>
                  編集
                  <% end %>
                  </td>
                  <% end %>
                  <% if user_signed_in? && current_user != @user %>
                     <% if current_user.active_relationships.exists?(target_user_id: @user.id) %>
                        <%= link_to 'フォローを外す', [@user, :follow], class: "button",method: :delete %>
                     <% else %>
                        <%= link_to 'フォロー', [@user, :follow],class: "button", method: :post %>
                     <% end %>
                  <% end %>
               </div>
            </div>
         </article>
      </div>
      </main>
   </div>
   <div class ="container">
      <div class="columns is-mobile is-centered">
         <div class="tabs">
            <ul>
               <li>
                  <%= link_to "投稿", user_path(@user)  %>
                  <%=@user.posts.count%>
               </li>
               <li>
                  <%= link_to "お気に入り", favorite_path(@user) %>
                  <%=@user.favorites.count%>
               </li>
               <li>
                  <%= link_to "フォロー", user_followings_path(@user)  %>
                  <%=@user.followings.count%>
               </li>
               <li>
                  <%= link_to "フォロワー", user_followers_path(@user)  %>
                  <%=@user.followers.count%>
               </li>
            </ul>
         </div>
      </div>
   </div>   

      
<div class ="container">
   <div class="columns is-mobile is-centered">
      <div class="column is-four-fifths">
         <div class="box">
            <div class="container">
               <h1 class="title has-text-centered mb-4">
                  <%= @user.username %>の投稿一覧
               </h1>
            </div>
            <% @user.posts.each do |post|%>
               <div class="box media mb-0 mt-0">
                  <figure class="media-left">
                     <p class="image is-32x32">
                        <%= link_to user_path(post.user_id) do %>
                           <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.png" %>
                        <% end %>
                     </p>
                  </figure>
                  <div class="media-content">
                     <%= link_to user_path(post.user_id) do %>
                        <%= post.user.username %>さん：
                     <% end %>
                     <strong>
                        <%= link_to post_path(post) do %>
                           <%= post.title %>
                        <% end %>
                     </strong>
                     <% if post.image_id == nil %>
                     <% else %>
                        <%= link_to post_path(post) do %>
                           画像あり
                        <% end %>
                     <% end %>
                     <div class ="has-text-right is-size-7">
                        <%= link_to post_path(post) do %>
                           <span class="icon is-small"><i class="fas fa-reply"></i></span>
                           <%= post.comments.count %>
                        <% end %>
                        <% if user_signed_in? %> 
                           <% if current_user.already_favorited?(post)%>
                              <%= link_to post_favorites_path(post), method: :delete do %>
                                 <span style="color: #ff5252"><span style="font-size: 100%"><i class="fa fa-heart faa-wrench animated-hover"></i></span></span>
                              <% end %>
                           <% else %>
                              <%= link_to post_favorites_path(post), method: :post do %>
                                 <i class ="far fa-heart faa-wrench animated-hover"></i>
                              <% end %>
                           <% end %>
                           <%= post.favorites.count %>
                        <% else %>
                           <%= link_to post_favorites_path(post), method: :delete do %>
                              <i class ="far fa-heart faa-wrench animated-hover"></i>
                              <%= post.favorites.count %>
                           <% end %>
                        <% end %>
                        <%= link_to post_path(post) do %>
                           詳細
                        <% end %>
                        <% if current_user == post.user %>
                           <%= link_to post_path(post), method: :delete, data:{confirm: "削除しますか？"} do %>
                              削除
                           <% end %>
                        <% end %>
                        <%= post.updated_at.strftime("%Y-%m-%d %H:%M") %>投稿
                     </div>
                  </div>
               </div>
            <% end %>
         </div>
     </div>
   </div>
</div>