config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  resources :favorites, only:[:show]
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :house_makers, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  resources :users do
    resource :follow,only: [:create, :destroy]
    resources :followings,only: [:index] 
    resources :followers,only: [:index] 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'

  validates :target_user_id, uniqueness: { scope: :user_id }
end

app/models/house_maker.rb
class HouseMaker < ApplicationRecord
  has_many :reviews, dependent: :destroy
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 100 }
  with_options presence: true do
    validates :body, :title

  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :house_maker
  validates :score,:content, presence: true, length: { maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  attachment :profile_image
  has_many :posts,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  validates :username, presence: true, length: { maximum: 10 }
  validates :profile, {length: {maximum: 24}}
  validates :maker_name, {length: {maximum: 12}}


  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end
  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def new_guest
    guest = User.find_or_create_by!(email: 'test@test.com') do |user|
      guest.password = SecureRandom.urlsafe_base64
    end
    sign_in guest
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order("id DESC").page(params[:page]).per(5)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    if @comment.save
      redirect_to post_path(@post)
    else 
      render :show 
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else 
      render :new 
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
    redirect_to post_path(@post)
    else 
      render :edit
    end
  end


  def edit
    @post= Post.find(params[:id])
    if @post.user != current_user
      redirect_to posts_path, alert: "不正なアクセスです"
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end


  private
  def post_params
    params.require(:post).permit(:title,:body,:image)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  
  def index
    
    @house_maker = HouseMaker.find(params[:house_maker_id])
    @reviews = @house_maker.reviews.all.page(params[:page]).per(5)
    
    
  end
  

  def create
    
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to house_maker_reviews_path(@review.house_maker)
    else
      @house_maker = HouseMaker.find(params[:house_maker_id])
      render "house_makers/show"
    end
  end
  

  private
  def review_params
    params.require(:review).permit(:house_maker_id, :score, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/house_makers_helper.rb
module HouseMakersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_form.html.erb
<p class ="lis-size-4 mb-3">レビューを書く</p>
<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>  
<div class="rating-box mt-3">
  <%= form_with model: review, url: house_maker_reviews_path(house_maker), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class ="ml-3 rating-value-display"><span id ="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :house_maker_id, value: house_maker.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_area :content, class: "textarea"%>
    <%= f.submit "保存", class: "button mt-3"%>
    <div class="columns is-mobile is-centered">
      <%= link_to "他のレビューも見る", house_maker_reviews_path(house_maker), class: "button" %>
      
    </div>
  <% end %>
</div>

<%= javascript_include_tag 'reviews.js' %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-mobile is-centered">
      <div class="column is-half">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title is-centered">
              <%= @house_maker.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @house_maker.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @house_maker.avg_score %>点（<%= @house_maker.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<section class="section">
  <div class ="container">
    <div class="columns is-mobile is-centered">
        <div class="column is-four-fifths">
          <div class="box">
              <div class="container">
                <h1 class="title has-text-centered mb-4">
                <%= @house_maker.name %>の評価
                </h1>
              </div>
              <% @reviews.each do |review| %>
                <div class="box media mb-0 mt-0">
                    <figure class="media-left">
                      <p class="image is-32x32">
                          <%= link_to user_path(review.user_id) do %>
                            <%= attachment_image_tag review.user, :profile_image, fallback: "no-image.png" %>
                          <% end %>
                      </p>
                    </figure>
                    <div class="media-content">
                      <%= link_to user_path(review.user_id) do %>
                          <%= review.user.username %>さん
                      <% end %>
                          投稿日：<%= review.updated_at.strftime("%Y-%m-%d %H:%M") %>
                      <% if current_user == review.user %>
                        <%= link_to post_path(review), method: :delete, data:{confirm: "削除しますか？"} do %>
                          削除
                        <% end %>
                      <% end %>
                      <div class="star-rating mt-1 ">
                        <div class="star-rating-front" style="width: <%= review.score * 20 %>%">★★★★★</div>
                        <div class="star-rating-back">★★★★★</div>
                      </div>
                                      <div class ="has-text-right">
                    <p class="card-header-title ">
                    評価：<%= review.score %>点
                    </p>
                  </div>
                      <div class="has-text-centered">
                      <%= review.content %>
                      </div>
                    </div>
                </div>
              <% end %>
              <div class="card mt-3 mb-0">
                <%= paginate @reviews,class: "pagination is-centered" %>
              </div>
          </div>
      </div>
    </div>
  </div>
</section>
<div class="columns is-mobile is-centered">
  <%= link_to "一覧に戻る", house_makers_path, class: "button mb-6" %>
</div>
<div class="columns is-mobile is-centered">
  <%= link_to house_maker_path(@house_maker), class: "button mb-6" do %>
  <%=@house_maker.name%>のレビューを書く
  <% end %>
</div>