config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  resources :favorites, only:[:show]
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  resources :users
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :house_makers, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
  end
  resources :users do
    resource :follow,only: [:create, :destroy]
    resources :followings,only: [:index] 
    resources :followers,only: [:index] 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 100 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'

  validates :target_user_id, uniqueness: { scope: :user_id }
end

app/models/house_maker.rb
class HouseMaker < ApplicationRecord
  has_many :reviews, dependent: :destroy
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 100 }
  with_options presence: true do
    validates :body, :title

  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :house_maker
  validates :score,:content, presence: true, length: { maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  attachment :profile_image
  has_many :posts,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  validates :username, presence: true, length: { maximum: 10 }
  validates :profile, {length: {maximum: 24}}
  validates :maker_name, {length: {maximum: 12}}


  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end
  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def new_guest
    guest = User.find_or_create_by!(email: 'test@test.com') do |user|
      guest.password = SecureRandom.urlsafe_base64
    end
    sign_in guest
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/house_makers_helper.rb
module HouseMakersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/9a773ab785.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
  </head>

  <body>
  
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="navbar-brand ">
        <p class="navbar-item">
          <%= link_to root_path do %>
            <strong class="is-size-3" style="font-family: cursive; color: black;">Review House</strong>
          <% end %>
        </p>
          <div id="nav-drawer" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <input id="nav-input" type="checkbox" class="navbar-burger burger" class="nav-unshown">
            <div id="nav-open" for="nav-input" ><span></span></div>
            <label class="nav-unshown" id="nav-close" for="nav-input"></label>
            <div id="nav-content">
              <% if user_signed_in? %>
              <p class="navbar-item">ようこそ
              <%= link_to user_path(current_user) do %>
              <%= current_user.username %> 
              <% end %>
              さん
              </p>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to user_path(current_user) ,class: "button" do  %>
                マイページ
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  ログアウト
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  ログイン
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  新規登録
                <% end %>
              <% end %>
              <%= link_to house_makers_path, class: "navbar-item" do %>
                ハウスメーカー一覧
              <% end %>
              <%= link_to users_path, class: "navbar-item" do %>
                ユーザー一覧
              <% end %>
              <%= link_to posts_path, class: "navbar-item" do %>
                投稿一覧
              <% end %>
              <%= link_to new_post_path, class: "navbar-item" do %>
                新規投稿
              <% end %>
            </div>
          </div>


      </div>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to house_makers_path, class: "navbar-item" do %>
            ハウスメーカー一覧
          <% end %>
          <%= link_to users_path, class: "navbar-item" do %>
            ユーザー一覧
          <% end %>
          <%= link_to posts_path, class: "navbar-item" do %>
            投稿一覧
          <% end %>
          <%= link_to new_post_path, class: "navbar-item" do %>
            新規投稿
          <% end %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <% if user_signed_in? %>
              <p class="navbar-item">ようこそ
              <%= link_to user_path(current_user) do %>
              <%= current_user.username %> 
              <% end %>

              さん
              </p>
            <% end %>
            <div class="buttons">
              <% if user_signed_in? %>
                <%= link_to user_path(current_user) ,class: "button" do  %>
                マイページ
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "button" do %>
                  ログアウト
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class: "button" do %>
                  ログイン
                <% end %>
                <%= link_to new_user_registration_path, class: "button" do %>
                  新規登録
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>